const router =  require('koa-router')();
const signIn = require('../controller/usr-sign-in')
const signUp  = require('../controller/usr-sign-up')
const { deleteSeleWord, addSelWord, getAllSelWords,createSelWord,examSubject,stuSubject,updateStuSelwords,updateTestSelwords} = require('../controller/sel-words')
const {deleteWord, updateWord, addWord, searchWord,searchWordById} = require('../controller/all-words')
const {getUsrInfo, setFlag} = require('../controller/usr-info')
const {jinshan} = require('../controller/getKing')
const {recommend} = require('../controller/recommend')
const routers =  router.post('/api/signin',signIn)
                       .post('/api/signup',signUp)
                       .get('/api/search', searchWord)
                       .get('/api/usr', getUsrInfo)
                       .post('/api/alreadyCreateSelWord',setFlag)
                       .post('/api/createSelWord',createSelWord)
                       .get('/api/getAllSelWord',getAllSelWords)
                       .post('/api/deleteSeleWord',deleteSeleWord)
                       .post('/api/addSelWord',addSelWord)
                       .post('/api/updateStuSelwords',updateStuSelwords)
                       .post('/api/updateTestSelwords',updateTestSelwords)
                       .get('/api/testSubject', examSubject)
                       .get('/api/stuSubject',stuSubject)
                       .post('/api/addIntoWords',addWord)
                       .post('/api/deleteWords',deleteWord)
                       .post('/api/updateWord',updateWord)
                       .get('/api/getWordById',searchWordById)
                       .get('/api/jinshan',jinshan)
                       .post('/api/recommend',recommend)
module.exports = routers